
files=$(find ./*/* -print)

echo $files

depth/beat/drum 
depth/bounce/basketball 
depth/bounce/volleyball 
depth/boxing/punching_bag 
depth/brush/broom 
depth/brush/brushes 
depth/brush/cosmetic_brushes 
depth/brush/toothbrush 
depth/contain_1/backpack 
depth/contain_1/gift_box 
depth/contain_1/handbag 
depth/contain_1/purse 
depth/contain_1/pushchair 
depth/contain_1/shopping_trolley 
depth/contain_1/storage_box 
depth/contain_1/suitcase 
depth/contain_2/beaker 
depth/contain_2/beer_bottle 
depth/contain_2/bowl 
depth/contain_2/cup_or_mug 
depth/contain_2/milk_can 
depth/contain_2/pitcher 
depth/contain_2/soap_dispenser 
depth/contain_2/vase 
depth/contain_2/watering_can 
depth/contain_3/bowl 
depth/contain_3/frying_pan 
depth/contain_3/plate 
depth/crutches/crutch 
depth/crutches/umbrella 
depth/cut/knife 
depth/cut/scissors 
depth/fork/fork 
depth/hit/axe 
depth/hit/baseball_bat 
depth/hit/hammer 
depth/hit/Hoe 
depth/hit/rolling_pin 
depth/jump/skateboard 
depth/jump/skis 
depth/jump/snowboard 
depth/jump/surfboard 
depth/kick/punching_bag 
depth/kick/rugby_ball 
depth/kick/soccer_ball 
depth/lie/baby_bed 
depth/lie/bench 
depth/lie/pushchair 
depth/lie/rocking_chair 
depth/lie/sofa 
depth/lift/dumbbell 
depth/look_out/binoculars 
depth/mix/chopsticks 
depth/mix/soup_ladle 
depth/mix/spatula 
depth/mix/spoon 
depth/mix/whisk 
depth/pick_up/chopsticks 
depth/play_1/cello 
depth/play_1/erhu_fiddle 
depth/play_1/viola 
depth/play_1/violin 
depth/play_2/banjo 
depth/play_2/guitar 
depth/play_2/harp 
depth/play_2/pipa 
depth/play_2/zither 
depth/play_3/Accordion 
depth/play_3/electronic_organ 
depth/play_3/piano 
depth/play_4/cucurbit_flute 
depth/play_4/flute 
depth/play_4/frenchhorn 
depth/push_and_pull/bicycle 
depth/push_and_pull/motorbike 
depth/push_and_pull/pushchair 
depth/push_and_pull/shopping_trolley 
depth/push_and_pull/suitcase 
depth/push_and_pull/wheelchair 
depth/ride/bicycle 
depth/ride/motorbike 
depth/roll_dough/rolling_pin 
depth/rolling/baseball 
depth/rolling/croquet_ball 
depth/rolling/golf_ball 
depth/rolling/table_tennis_ball 
depth/rolling/tennis_ball 
depth/scoop/soup_ladle 
depth/scoop/spatula 
depth/scoop/spoon 
depth/shelter/umbrella 
depth/sit/bench 
depth/sit/rocking_chair 
depth/sit/sofa 
depth/sit/stool 
depth/sit/swing 
depth/sit/wheelchair 
depth/standing/desk 
depth/standing/stool 
depth/support/desk 
depth/swing/badminton_racket 
depth/swing/baseball_bat 
depth/swing/golf_clubs 
depth/swing/table_tennis 
depth/swing/tennis 
depth/take_photo/camera 
depth/throw/baseball 
depth/throw/basketball 
depth/throw/darts 
depth/throw/discus 
depth/throw/frisbee 
depth/throw/javelin 
depth/throw/rugby_ball 
depth/throw/soccer_ball 
depth/throw/weight_throw 
depth/wear_1/hat 
depth/wear_1/helmet 
depth/wear_2/glasses 
depth/wear_3/boots 
depth/wear_3/high_heels 
depth/wear_3/skating_shoes 
depth/wear_3/slippers 
depth/wear_3/sports_shoes 
depth/wear_4/glove 
depth/write/pen 
depth/write/writing_brush